on: #Definde los eventos que se van a desencadenar al ejecutar el workflow
  push: #Indica que el workflow se activara cuando se realice un push al repositorio
    branches: #Especifica que el workflow solo se ejecuta cuando el push se realice en la rama main
      - main

jobs: #define los trabajos que se van a realizar
  print-hello: #Nombre del trabajo
    runs-on: ubuntu-latest #Indica el tipo de MV en la que se ejecuta el trabajo
    steps: #Define los pasos que se van a ejecutar dentro del trabajo
      - run: echo "Hello world!" #El paso que se va a ejecutar. En este caso, impresión por pantalla del mensaje "Hello world!""
